group=net.silthus
packageName=net.silthus.template
pluginName=TemplatePlugin
commandName=template
author=Silthus
version=6.0.0-SNAPSHOT
javaVersion=25
paperApiVersion=26.2.build.129-stable
apiVersion=26.2
mockBukkitVersion=4.116.1
junitVersion=6.1.3
jacocoVersion=0.8.15
org.gradle.caching=true
org.gradle.configuration-cache=true
